import type { Pack, PackTemplate, Recurrence, PackGradient } from "./packs";

const T = (
  id: string,
  text: string,
  emoji: string,
  categoryId: string,
  defaultTimeOfDay: string,
  defaultRecurrence: Recurrence,
  defaultNotify: "notification" | "alarm" = "notification",
  benefit?: string,
): PackTemplate => ({ id, text, emoji, categoryId, defaultTimeOfDay, defaultRecurrence, defaultNotify, benefit });

const mkPack = (
  id: string,
  name: string,
  emoji: string,
  shortDesc: string,
  longDesc: string,
  primaryCategoryId: string,
  gradient: PackGradient,
  benefitBullets: string[],
  recoveryBenefit: string,
  tags: string[],
  templates: PackTemplate[],
): Pack => ({
  id, name, emoji, shortDesc, longDesc, primaryCategoryId, gradient,
  benefitBullets,
  howItWorks: [
    "Install the pack — defaults are already smart.",
    "Tweak any reminder text or time so it fits you.",
    "MinDrop nudges you at the right moment, every time.",
  ],
  recoveryBenefit,
  visibility: "published", tags,
  templates,
});

export const packsSeed: Pack[] = [
  mkPack("parenting-y1", "Parenting · Year 1", "🍼", "First-year baby essentials", "All the tiny daily things first-time parents shouldn't have to hold in their head.",
    "meds", "rose",
    ["Never miss a vitamin drop or feed log", "Stay ahead of pediatrician dates", "Sleep more, juggle less"],
    "Kept the baby on track without you having to remember every little thing.",
    ["parenting", "baby"],
    [
      T("p1a", "Give baby Vitamin D drops", "💧", "Medication", "09:00", "daily", "notification"),
      T("p1b", "Tummy time (15 min)", "🤸", "Workout", "10:30", "daily"),
      T("p1c", "Restock diapers", "📦", "Errand", "18:00", "weekly"),
      T("p1d", "Sterilize bottles", "🍼", "Stuff", "21:00", "daily"),
      T("p1e", "Log feed times today", "📝", "Other", "20:00", "daily"),
      T("p1f", "Pediatrician check-up", "🩺", "Call", "09:30", "monthly", "alarm"),
      T("p1g", "Vaccination due — confirm date", "💉", "Event", "10:00", "monthly", "alarm"),
      T("p1h", "Wash baby laundry", "🧺", "Stuff", "11:00", "weekly"),
      T("p1i", "Buy formula", "🍼", "Errand", "17:00", "weekly"),
      T("p1j", "Cut baby's nails", "✂️", "Stuff", "19:00", "weekly"),
      T("p1k", "Bath time", "🛁", "Stuff", "19:30", "daily"),
      T("p1l", "Read a bedtime story", "📖", "Read/Watch", "20:30", "daily"),
    ]),

  mkPack("parenting-toddler", "Parenting · Toddler", "🧒", "Ages 2–4 routines", "Daycare, snacks, naps, tantrums — the toddler operating system.",
    "event", "peach",
    ["Smoother mornings, fewer meltdowns", "Daycare bag never forgotten", "Catch milestones before they pass"],
    "Kept the toddler routine running so your day didn't fall apart.",
    ["parenting", "toddler"],
    [
      T("p2a", "Pack daycare bag", "🎒", "Stuff", "07:30", "daily"),
      T("p2b", "Refill water bottle", "💧", "Stuff", "07:45", "daily"),
      T("p2c", "Nap window — quiet mode", "😴", "Other", "13:00", "daily"),
      T("p2d", "Library storytime", "📚", "Event", "10:00", "weekly"),
      T("p2e", "Grocery: kid snacks", "🍎", "Errand", "18:00", "weekly"),
      T("p2f", "Pediatric dental check", "🦷", "Event", "10:00", "monthly", "alarm"),
      T("p2g", "New shoe size check", "👟", "Stuff", "11:00", "monthly"),
      T("p2h", "Trim toddler hair", "💇", "Errand", "11:00", "monthly"),
      T("p2i", "Vitamin gummy", "🍬", "Medication", "08:30", "daily"),
      T("p2j", "Plan weekend activity", "🎨", "Idea", "17:00", "weekly"),
      T("p2k", "Pay daycare fee", "💳", "Bill", "09:00", "monthly", "alarm"),
      T("p2l", "Restock wipes", "📦", "Errand", "18:00", "weekly"),
    ]),

  mkPack("school-parent", "School Parent", "🎒", "K–12 school logistics", "PTA, permission slips, exam weeks — everything school throws at you.",
    "event", "sky",
    ["Never miss a permission slip", "Exam-week ready, not panicked", "Lunchbox packed before chaos"],
    "Kept school life organised — no last-minute scrambles.",
    ["school", "parent"],
    [
      T("p3a", "Pack school lunch", "🍱", "Meal", "07:00", "daily"),
      T("p3b", "Sign homework diary", "✍️", "Stuff", "20:00", "daily"),
      T("p3c", "PTA meeting", "🧑‍🏫", "Event", "18:00", "monthly", "alarm"),
      T("p3d", "Pay school fees", "💳", "Bill", "09:00", "monthly", "alarm"),
      T("p3e", "Sports day kit ready", "🏃", "Stuff", "07:00", "weekly"),
      T("p3f", "Buy stationery", "✏️", "Errand", "17:00", "monthly"),
      T("p3g", "Check report card", "📑", "Read/Watch", "19:00", "monthly"),
      T("p3h", "Teacher meeting prep", "📝", "Work", "08:00", "monthly", "alarm"),
      T("p3i", "Exam revision block", "📚", "Read/Watch", "17:00", "weekly"),
      T("p3j", "Pack project supplies", "🎨", "Stuff", "19:00", "weekly"),
      T("p3k", "School bus pickup", "🚌", "Event", "07:30", "daily", "alarm"),
      T("p3l", "Read with kid (20 min)", "📖", "Read/Watch", "20:30", "daily"),
    ]),

  mkPack("travel-prep", "Travel Prep", "✈️", "Trip checklist + reminders", "Everything you forget right before a flight — handled.",
    "travel", "sky",
    ["No more 'did I pack my charger?'", "Visa & checkin reminders on time", "Land remembering hotel details"],
    "Got you on the plane with everything you needed — passport included.",
    ["travel", "trip"],
    [
      T("p4a", "Check-in online", "🛫", "Travel", "06:00", "once", "alarm"),
      T("p4b", "Pack passport & ID", "🪪", "Stuff", "20:00", "once"),
      T("p4c", "Charge all devices", "🔌", "Stuff", "21:00", "once"),
      T("p4d", "Confirm hotel booking", "🏨", "Call", "10:00", "once"),
      T("p4e", "Buy travel insurance", "🛡️", "Bill", "10:00", "once"),
      T("p4f", "Currency exchange", "💱", "Errand", "11:00", "once"),
      T("p4g", "Download offline maps", "🗺️", "Stuff", "20:00", "once"),
      T("p4h", "Print boarding pass", "🖨️", "Stuff", "07:00", "once"),
      T("p4i", "Set out-of-office reply", "📧", "Email", "17:00", "once"),
      T("p4j", "Cab to airport", "🚖", "Travel", "05:00", "once", "alarm"),
      T("p4k", "Pack chargers + adapters", "🔋", "Stuff", "20:30", "once"),
      T("p4l", "Tell neighbor / water plants", "🌱", "Person", "18:00", "once"),
    ]),

  mkPack("daily-wellness", "Daily Wellness", "🌿", "Simple healthy habits", "Tiny daily actions that stack into a calmer, healthier you.",
    "workout", "mint",
    ["Build streaks without thinking", "Hydrate, stretch, breathe — on cue", "Sleep window protected"],
    "Showed up for your body every day — even on busy ones.",
    ["wellness", "health"],
    [
      T("p5a", "Drink a glass of water", "💧", "Other", "08:00", "daily"),
      T("p5b", "10-minute stretch", "🧘", "Workout", "07:30", "daily"),
      T("p5c", "Take multivitamin", "💊", "Medication", "09:00", "daily"),
      T("p5d", "Step away from screen", "👀", "Other", "14:00", "daily"),
      T("p5e", "Walk after lunch", "🚶", "Workout", "13:30", "daily"),
      T("p5f", "Wind-down time", "🌙", "Other", "22:00", "daily", "alarm"),
      T("p5g", "Journal one line", "📓", "Idea", "21:30", "daily"),
      T("p5h", "Sunlight (10 min)", "☀️", "Other", "08:30", "daily"),
      T("p5i", "Weigh-in (weekly)", "⚖️", "Other", "07:00", "weekly"),
      T("p5j", "Meal prep block", "🥗", "Meal", "17:00", "weekly"),
      T("p5k", "Floss tonight", "🦷", "Stuff", "22:15", "daily"),
      T("p5l", "Refill water bottle", "🚰", "Stuff", "12:00", "daily"),
    ]),

  mkPack("fitness-starter", "Fitness Starter", "🏋️", "4-week beginner plan", "A gentle ramp into a real fitness habit, with rest days built in.",
    "workout", "mint",
    ["Show up without overthinking", "Rest days are reminders too", "Progress photos, monthly"],
    "Helped you keep the streak — even the weeks life got in the way.",
    ["fitness", "habit"],
    [
      T("p6a", "Strength session", "🏋️", "Workout", "07:00", "weekly"),
      T("p6b", "Cardio · 20 min", "🏃", "Workout", "07:00", "weekly"),
      T("p6c", "Mobility / yoga", "🧘", "Workout", "07:30", "weekly"),
      T("p6d", "Rest day — eat well, sleep early", "🛌", "Other", "09:00", "weekly"),
      T("p6e", "Log workout in journal", "📓", "Other", "20:00", "daily"),
      T("p6f", "Protein at every meal", "🍳", "Meal", "08:00", "daily"),
      T("p6g", "Progress photo", "📸", "Other", "07:00", "monthly"),
      T("p6h", "Plan next week's sessions", "🗓️", "Idea", "19:00", "weekly"),
      T("p6i", "Gym bag ready by door", "🎒", "Stuff", "21:00", "daily"),
      T("p6j", "Track water intake", "💧", "Other", "10:00", "daily"),
      T("p6k", "Stretch before bed", "🌙", "Workout", "22:00", "daily"),
      T("p6l", "Weigh-in & measurements", "⚖️", "Other", "07:00", "weekly"),
    ]),

  mkPack("mental-checkins", "Mental Check-ins", "🧠", "Gentle self check-ins", "Small prompts to notice how you're actually doing — before it builds up.",
    "idea", "lilac",
    ["Notice mood shifts early", "Therapy session prep prompts", "Gratitude moments on cue"],
    "Gave your mind a moment to land — instead of running on autopilot.",
    ["mental", "wellbeing"],
    [
      T("p7a", "How am I feeling right now?", "🫶", "Idea", "11:00", "daily"),
      T("p7b", "Three things I'm grateful for", "🙏", "Idea", "21:00", "daily"),
      T("p7c", "Box-breathing · 2 min", "🌬️", "Other", "15:00", "daily"),
      T("p7d", "Therapy session today", "🛋️", "Event", "17:00", "weekly", "alarm"),
      T("p7e", "Therapy prep — what came up?", "📓", "Idea", "16:30", "weekly"),
      T("p7f", "Call a friend just to chat", "📞", "Call", "18:00", "weekly"),
      T("p7g", "Step outside, no phone", "🌳", "Other", "16:00", "daily"),
      T("p7h", "Take meds (mental health)", "💊", "Medication", "08:00", "daily", "alarm"),
      T("p7i", "No-screen hour before bed", "📵", "Other", "21:30", "daily"),
      T("p7j", "Write the worry, close the loop", "✍️", "Idea", "22:00", "daily"),
      T("p7k", "One small kindness today", "💝", "Promise", "12:00", "daily"),
      T("p7l", "Mood weather check (1–10)", "🌤️", "Other", "20:00", "daily"),
    ]),

  mkPack("work-focus", "Work Focus", "💼", "Deep work + follow-ups", "Protect your attention, close loops, look on top of things.",
    "work", "sand",
    ["Inbox doesn't run your day", "Follow-ups never slip", "Deep-work blocks defended"],
    "Made you look (and feel) on top of every commitment.",
    ["work", "focus"],
    [
      T("p8a", "Deep work block", "🧠", "Work", "09:30", "daily", "alarm"),
      T("p8b", "Inbox triage (15 min)", "📧", "Email", "08:30", "daily"),
      T("p8c", "Weekly review", "📊", "Work", "16:00", "weekly"),
      T("p8d", "1:1 with manager prep", "🤝", "Work", "09:00", "weekly"),
      T("p8e", "Follow up on open thread", "🔁", "Email", "11:00", "daily"),
      T("p8f", "Submit timesheet", "🕒", "Work", "17:00", "weekly", "alarm"),
      T("p8g", "Update task tracker", "✅", "Work", "17:30", "daily"),
      T("p8h", "Plan tomorrow (3 priorities)", "🎯", "Work", "18:00", "daily"),
      T("p8i", "Stand-up notes", "🗒️", "Work", "09:55", "daily"),
      T("p8j", "Drink water at desk", "💧", "Other", "11:00", "daily"),
      T("p8k", "Walk between meetings", "🚶", "Workout", "14:00", "daily"),
      T("p8l", "Friday wins recap", "🏆", "Work", "16:30", "weekly"),
    ]),

  mkPack("job-hunt", "Job Hunt", "🎯", "Search, apply, follow up", "Keep applications, recruiters, and interviews from blurring together.",
    "work", "sky",
    ["No application falls through cracks", "Follow up at the right week", "Interview prep on a schedule"],
    "Kept the hunt structured so you stayed visible — not desperate.",
    ["jobs", "career"],
    [
      T("p9a", "Apply to 2 roles today", "📝", "Work", "10:00", "daily"),
      T("p9b", "Follow up on application", "🔁", "Email", "11:00", "weekly"),
      T("p9c", "LinkedIn — connect with 3 people", "🔗", "Person", "12:00", "weekly"),
      T("p9d", "Interview prep block", "🎤", "Work", "19:00", "weekly", "alarm"),
      T("p9e", "Update resume + portfolio", "📄", "Stuff", "20:00", "weekly"),
      T("p9f", "Send thank-you after interview", "📧", "Email", "18:00", "once"),
      T("p9g", "Recruiter check-in call", "📞", "Call", "11:00", "weekly"),
      T("p9h", "Practice one common question", "🗣️", "Read/Watch", "19:30", "daily"),
      T("p9i", "Refresh saved searches", "🔍", "Stuff", "09:00", "weekly"),
      T("p9j", "Mock interview with friend", "👥", "Person", "18:00", "weekly"),
      T("p9k", "Negotiation prep", "💬", "Work", "20:00", "once"),
      T("p9l", "Celebrate a small win", "🎉", "Promise", "21:00", "weekly"),
    ]),

  mkPack("money-bills", "Money & Bills", "💳", "Bills, EMIs, savings", "Never get blindsided by a due date or auto-renewal again.",
    "bill", "sand",
    ["No late fees, ever", "Subscriptions you actually use", "Savings move before you spend"],
    "Kept your money tidy — no surprise charges, no missed dues.",
    ["money", "bills"],
    [
      T("p10a", "Pay credit card", "💳", "Bill", "10:00", "monthly", "alarm"),
      T("p10b", "Rent / EMI due", "🏠", "Bill", "09:00", "monthly", "alarm"),
      T("p10c", "Electricity bill", "💡", "Bill", "10:00", "monthly", "alarm"),
      T("p10d", "Internet bill", "🌐", "Bill", "10:00", "monthly"),
      T("p10e", "Review subscriptions", "📺", "Bill", "11:00", "monthly"),
      T("p10f", "Move money to savings", "🏦", "Other", "10:00", "monthly", "alarm"),
      T("p10g", "Check credit score", "📈", "Stuff", "10:00", "monthly"),
      T("p10h", "Insurance renewal", "🛡️", "Bill", "09:00", "monthly", "alarm"),
      T("p10i", "Tax document drop", "🧾", "Stuff", "10:00", "monthly"),
      T("p10j", "Review last week's spend", "🧮", "Stuff", "18:00", "weekly"),
      T("p10k", "Set next month's budget", "📊", "Idea", "19:00", "monthly"),
      T("p10l", "Cancel that free trial", "✂️", "Bill", "09:00", "once", "alarm"),
    ]),

  mkPack("home-maintenance", "Home Maintenance", "🏡", "Upkeep without spreadsheets", "The seasonal, quarterly, and 'I always forget' home tasks.",
    "stuff", "sand",
    ["Filters changed before they're nasty", "AC serviced before it breaks", "Smoke alarm always alive"],
    "Kept the house running quietly — nothing broke at the worst moment.",
    ["home", "house"],
    [
      T("p11a", "Replace water filter", "💧", "Stuff", "10:00", "monthly"),
      T("p11b", "Vacuum the house", "🧹", "Stuff", "11:00", "weekly"),
      T("p11c", "Clean fridge", "🧊", "Stuff", "11:00", "monthly"),
      T("p11d", "Test smoke alarm", "🚨", "Stuff", "10:00", "monthly", "alarm"),
      T("p11e", "Service AC", "❄️", "Errand", "11:00", "monthly"),
      T("p11f", "Take out trash", "🗑️", "Stuff", "20:00", "weekly"),
      T("p11g", "Water bills", "💧", "Bill", "10:00", "monthly"),
      T("p11h", "Society maintenance", "🏢", "Bill", "10:00", "monthly", "alarm"),
      T("p11i", "Pest control", "🪲", "Errand", "11:00", "monthly"),
      T("p11j", "Restock cleaning supplies", "🧴", "Errand", "17:00", "monthly"),
      T("p11k", "Change bedsheets", "🛏️", "Stuff", "11:00", "weekly"),
      T("p11l", "Deep clean bathroom", "🚿", "Stuff", "11:00", "weekly"),
    ]),

  mkPack("cooking-groceries", "Cooking & Groceries", "🍳", "Meal plan + shop list", "Get out of the 'what's for dinner' loop without the spreadsheet.",
    "meal", "peach",
    ["Weeknights know what's cooking", "Groceries match the plan", "Leftovers don't go to waste"],
    "Made the kitchen calmer — and the takeaway tab smaller.",
    ["food", "cooking"],
    [
      T("p12a", "Plan this week's dinners", "📋", "Meal", "11:00", "weekly"),
      T("p12b", "Grocery run", "🛒", "Errand", "17:00", "weekly"),
      T("p12c", "Sunday meal prep", "🥗", "Meal", "16:00", "weekly"),
      T("p12d", "Use up leftovers", "🍱", "Meal", "13:00", "weekly"),
      T("p12e", "Refill pantry staples", "🥫", "Errand", "17:30", "monthly"),
      T("p12f", "Try a new recipe", "👨‍🍳", "Idea", "19:00", "weekly"),
      T("p12g", "Order milk / dairy", "🥛", "Errand", "08:00", "weekly"),
      T("p12h", "Defrost meat", "🍖", "Meal", "08:00", "weekly"),
      T("p12i", "Sharpen knives", "🔪", "Stuff", "11:00", "monthly"),
      T("p12j", "Restock spices", "🧂", "Errand", "17:00", "monthly"),
      T("p12k", "Bake something for fun", "🧁", "Idea", "16:00", "weekly"),
      T("p12l", "Hydration: drink water now", "💧", "Other", "11:00", "daily"),
    ]),

  mkPack("pet-care", "Pet Care", "🐶", "Walks, vet, food", "Your pet doesn't read calendars — you do.",
    "pet", "peach",
    ["Walks happen even on busy days", "Vet visits not skipped", "Refills before the bowl empties"],
    "Kept your pet healthy and routine-happy.",
    ["pet"],
    [
      T("p13a", "Morning walk", "🚶", "Pet", "07:00", "daily"),
      T("p13b", "Evening walk", "🌆", "Pet", "18:30", "daily"),
      T("p13c", "Refill kibble", "🥣", "Errand", "17:00", "weekly"),
      T("p13d", "Tick / flea treatment", "🧴", "Medication", "10:00", "monthly", "alarm"),
      T("p13e", "Vet check-up", "🩺", "Event", "11:00", "monthly", "alarm"),
      T("p13f", "Vaccinations due", "💉", "Event", "10:00", "monthly", "alarm"),
      T("p13g", "Groom / bathe pet", "🛁", "Stuff", "11:00", "monthly"),
      T("p13h", "Clip nails", "✂️", "Stuff", "11:00", "monthly"),
      T("p13i", "Clean litter / cage", "🧹", "Stuff", "08:00", "daily"),
      T("p13j", "Play / training session", "🎾", "Pet", "17:00", "daily"),
      T("p13k", "Restock treats", "🦴", "Errand", "17:00", "monthly"),
      T("p13l", "Update tag / microchip info", "🪪", "Stuff", "10:00", "monthly"),
    ]),

  mkPack("elder-care", "Elder Care", "👵", "Caring for parents", "The medicine, doctor visits, and warm calls that matter most.",
    "meds", "rose",
    ["Meds on time, every day", "Doctor visits never forgotten", "A daily check-in call — kept"],
    "Quietly held the whole care routine together.",
    ["family", "elder"],
    [
      T("p14a", "Morning medication", "💊", "Medication", "08:00", "daily", "alarm"),
      T("p14b", "Evening medication", "💊", "Medication", "20:00", "daily", "alarm"),
      T("p14c", "Daily check-in call", "📞", "Call", "11:00", "daily"),
      T("p14d", "Doctor appointment", "🩺", "Event", "10:00", "monthly", "alarm"),
      T("p14e", "Refill prescription", "💊", "Errand", "11:00", "monthly", "alarm"),
      T("p14f", "Blood pressure log", "🩸", "Other", "09:00", "daily"),
      T("p14g", "Pay caregiver", "💳", "Bill", "10:00", "monthly", "alarm"),
      T("p14h", "Groceries for them", "🛒", "Errand", "11:00", "weekly"),
      T("p14i", "Help with bills / paperwork", "📑", "Stuff", "17:00", "monthly"),
      T("p14j", "Family video call", "📹", "Call", "19:00", "weekly"),
      T("p14k", "Schedule physiotherapy", "🦴", "Event", "10:00", "weekly"),
      T("p14l", "Visit in person", "🫂", "Event", "11:00", "weekly", "alarm"),
    ]),

  mkPack("student-life", "Student Life", "📚", "Lectures, assignments, exams", "Stay on top of deadlines without the all-nighters.",
    "work", "lilac",
    ["No assignment ambush", "Revision starts early", "Lectures actually attended"],
    "Kept term life under control — without the panic week.",
    ["student", "study"],
    [
      T("p15a", "Morning lecture", "🎓", "Event", "09:00", "daily", "alarm"),
      T("p15b", "Library study block", "📖", "Read/Watch", "15:00", "daily"),
      T("p15c", "Assignment due check", "📝", "Work", "20:00", "weekly", "alarm"),
      T("p15d", "Group project sync", "👥", "Call", "17:00", "weekly"),
      T("p15e", "Revision · 30 min", "✏️", "Read/Watch", "18:00", "daily"),
      T("p15f", "Tutor / TA office hours", "🧑‍🏫", "Event", "14:00", "weekly"),
      T("p15g", "Submit assignment", "📤", "Work", "21:00", "weekly", "alarm"),
      T("p15h", "Exam week prep starts", "🚨", "Work", "10:00", "monthly", "alarm"),
      T("p15i", "Pay tuition / fees", "💳", "Bill", "10:00", "monthly", "alarm"),
      T("p15j", "Renew library books", "📚", "Errand", "11:00", "monthly"),
      T("p15k", "Career fair / talk", "🎤", "Event", "16:00", "monthly"),
      T("p15l", "Sleep before 12", "🌙", "Other", "23:30", "daily", "alarm"),
    ]),

  mkPack("long-distance", "Long-Distance Love", "💌", "Stay close across time zones", "Tiny rituals that keep the spark alive when miles separate you.",
    "person", "rose",
    ["Good-morning texts on cue", "Date nights actually happen", "Care packages remembered"],
    "Kept the relationship warm even when the timezone wasn't kind.",
    ["love", "relationship"],
    [
      T("p16a", "Send a good-morning message", "🌅", "Person", "07:30", "daily"),
      T("p16b", "Plan virtual date night", "🎬", "Event", "20:00", "weekly", "alarm"),
      T("p16c", "Ask about their day", "💬", "Person", "21:00", "daily"),
      T("p16d", "Send a voice note", "🎙️", "Person", "12:00", "weekly"),
      T("p16e", "Mail a card / package", "📮", "Errand", "11:00", "monthly"),
      T("p16f", "Mark anniversary", "💍", "Event", "10:00", "monthly", "alarm"),
      T("p16g", "Book next visit", "✈️", "Travel", "11:00", "monthly"),
      T("p16h", "Watch movie together", "🍿", "Event", "21:30", "weekly"),
      T("p16i", "Cook same recipe over call", "🍳", "Meal", "19:30", "weekly"),
      T("p16j", "Share a song", "🎵", "Idea", "18:00", "daily"),
      T("p16k", "Photo of your day", "📸", "Person", "17:00", "daily"),
      T("p16l", "Plan a future trip together", "🗺️", "Idea", "20:00", "weekly"),
    ]),

  mkPack("wedding-planning", "Wedding Planning", "💍", "Months out to the big day", "All the moving parts of a wedding — without the spreadsheet sprawl.",
    "event", "rose",
    ["Vendor follow-ups on schedule", "Outfit + ring + RSVP — tracked", "Final-week checklist guarded"],
    "Kept your wedding planning calm — and the marriage starting strong.",
    ["wedding", "event"],
    [
      T("p17a", "Confirm venue payment", "🏛️", "Bill", "10:00", "monthly", "alarm"),
      T("p17b", "Follow up with photographer", "📸", "Call", "11:00", "weekly"),
      T("p17c", "Outfit fitting", "👗", "Event", "12:00", "monthly", "alarm"),
      T("p17d", "Send invites batch", "💌", "Email", "11:00", "weekly"),
      T("p17e", "Confirm RSVPs", "✅", "Stuff", "18:00", "weekly"),
      T("p17f", "Caterer tasting", "🍽️", "Event", "13:00", "monthly", "alarm"),
      T("p17g", "Buy rings", "💍", "Errand", "11:00", "once", "alarm"),
      T("p17h", "Marriage registration paperwork", "📑", "Stuff", "10:00", "once", "alarm"),
      T("p17i", "Honeymoon booking", "✈️", "Travel", "11:00", "once"),
      T("p17j", "Hair / makeup trial", "💄", "Event", "10:00", "monthly"),
      T("p17k", "Music playlist finalise", "🎶", "Idea", "20:00", "weekly"),
      T("p17l", "Thank-you notes after", "📝", "Email", "18:00", "once"),
    ]),

  mkPack("relocation", "New Move", "📦", "Relocation checklist", "Moving cities or just streets — every small task surfaced on time.",
    "stuff", "sky",
    ["Address updates not forgotten", "Utilities transferred cleanly", "First-week setup smoothed"],
    "Made the move feel handled — not chaotic.",
    ["move", "relocation"],
    [
      T("p18a", "Book movers", "🚚", "Call", "11:00", "once", "alarm"),
      T("p18b", "Get packing boxes", "📦", "Errand", "17:00", "once"),
      T("p18c", "Update address — bank", "🏦", "Stuff", "10:00", "once"),
      T("p18d", "Update address — gov ID", "🪪", "Stuff", "10:00", "once"),
      T("p18e", "Transfer electricity", "💡", "Bill", "10:00", "once", "alarm"),
      T("p18f", "Transfer internet", "🌐", "Bill", "10:00", "once"),
      T("p18g", "Change locks", "🔐", "Stuff", "11:00", "once"),
      T("p18h", "Buy curtains + essentials", "🪟", "Errand", "17:00", "once"),
      T("p18i", "Meet the neighbors", "👋", "Person", "18:00", "once"),
      T("p18j", "Find nearby grocer / chemist", "🏪", "Place", "11:00", "once"),
      T("p18k", "Register for local services", "📑", "Stuff", "10:00", "once"),
      T("p18l", "Take 'before' photos", "📸", "Other", "11:00", "once"),
    ]),

  mkPack("festivals-in", "Festivals & Birthdays", "🎂", "India-first occasions", "Diwali to Eid to birthdays — be the one who remembered.",
    "birthday", "peach",
    ["First to wish — always", "Gift ideas ready, not panicked", "Cards & sweets ordered in time"],
    "Made you the friend / family member who never missed an occasion.",
    ["india", "festival", "birthday"],
    [
      T("p19a", "Mom's birthday — plan", "🎂", "Birthday", "10:00", "monthly", "alarm"),
      T("p19b", "Dad's birthday — plan", "🎂", "Birthday", "10:00", "monthly", "alarm"),
      T("p19c", "Partner's birthday", "🎉", "Birthday", "09:00", "monthly", "alarm"),
      T("p19d", "Order sweets for Diwali", "🪔", "Errand", "11:00", "monthly"),
      T("p19e", "Wish Eid Mubarak", "🌙", "Person", "08:00", "monthly", "alarm"),
      T("p19f", "Holi colors & plans", "🎨", "Event", "09:00", "monthly"),
      T("p19g", "Rakhi to siblings", "🪢", "Person", "10:00", "monthly", "alarm"),
      T("p19h", "Anniversary gift idea", "💝", "Gift", "11:00", "monthly"),
      T("p19i", "Christmas gift list", "🎁", "Gift", "17:00", "monthly"),
      T("p19j", "Send New Year wishes", "🎆", "Person", "09:00", "once", "alarm"),
      T("p19k", "Book restaurant for birthday", "🍽️", "Call", "11:00", "monthly"),
      T("p19l", "Pick up cake", "🎂", "Errand", "17:00", "monthly", "alarm"),
    ]),

  mkPack("spiritual", "Spiritual & Mindful", "🕉️", "Quiet daily rituals", "Pauses, prayers, and reflection — built into the day.",
    "idea", "lilac",
    ["Daily practice without nagging", "Sacred days remembered", "Reflection prompts that land"],
    "Helped you carve out the quiet — even on noisy days.",
    ["spiritual", "mindful"],
    [
      T("p20a", "Morning meditation · 10 min", "🧘", "Other", "06:30", "daily"),
      T("p20b", "Evening prayer / chant", "🪔", "Other", "19:00", "daily"),
      T("p20c", "Read a verse / passage", "📖", "Read/Watch", "07:00", "daily"),
      T("p20d", "Light incense / diya", "🕯️", "Other", "18:30", "daily"),
      T("p20e", "Gratitude reflection", "🙏", "Idea", "21:30", "daily"),
      T("p20f", "Visit temple / place of worship", "🛕", "Event", "08:00", "weekly"),
      T("p20g", "Fast day check", "🍵", "Other", "06:00", "weekly", "alarm"),
      T("p20h", "Donate / give back", "💝", "Promise", "11:00", "monthly"),
      T("p20i", "Call a mentor / elder", "📞", "Call", "18:00", "monthly"),
      T("p20j", "Digital sabbath hour", "📵", "Other", "20:00", "weekly"),
      T("p20k", "Nature walk in silence", "🌳", "Workout", "07:00", "weekly"),
      T("p20l", "Reflect: what mattered this week?", "🪞", "Idea", "21:00", "weekly"),
    ]),
];
