#!/usr/bin/env node
// Consolidated Android Build Health Dashboard.
// Runs a data-driven list of checks and prints ONE report.
// Modes:
//   --doctor         → include host toolchain checks (JDK, Android SDK, etc.)
//   --phase=pre-sync → checks that must pass before `npx cap sync`
//   --phase=post-sync → checks that must pass after sync
//   --report-only    → never exit non-zero (informational)
import { readFile, readdir, stat } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { existsSync } from "node:fs";
import { discoverWebOutput } from "./lib/discover-web-output.mjs";
import { validateToolchain } from "./validate-toolchain.mjs";

const ROOT = process.cwd();
const args = new Set(process.argv.slice(2));
const phase = [...args].find((a) => a.startsWith("--phase="))?.split("=")[1] ?? "all";
const isDoctor = args.has("--doctor");
const reportOnly = args.has("--report-only");

const results = [];
function record(group, name, status, hint = "") {
  results.push({ group, name, status, hint });
}

async function pathExists(p) { try { await stat(p); return true; } catch { return false; } }
async function readSafe(p) { try { return await readFile(p, "utf8"); } catch { return null; } }

// ─── Checks ─────────────────────────────────────────────────────────────
async function checkWebBuild() {
  let out;
  try { out = await discoverWebOutput(ROOT); }
  catch (e) {
    record("Web build", "output dir", "fail", "run `npm run build:android`");
    record("Web build", "index.html", "fail", "");
    record("Web build", "assets/", "fail", "");
    return null;
  }
  record("Web build", "output dir", "pass", out.rel);
  record("Web build", "index.html", out.hasIndex ? "pass" : "warn",
    out.hasIndex ? "" : "will be generated by build:android");
  record("Web build", "assets/", out.entryJs ? "pass" : "fail",
    out.entryJs ? "" : "no JS entry — rerun build");
  return out;
}

async function checkAndroidBuild(out) {
  const manifestPath = path.resolve(ROOT, ".output/android-build-manifest.json");
  const hasManifest = await pathExists(manifestPath);
  record("Android build", "build manifest", hasManifest ? "pass" : "warn",
    hasManifest ? "" : "run `npm run build:android`");

  const webDir = path.resolve(ROOT, ".output/public");
  const hasWebDir = await pathExists(path.join(webDir, "index.html"));
  record("Android build", "webDir index.html", hasWebDir ? "pass" : "fail",
    hasWebDir ? "" : "run `npm run build:android`");

  if (hasWebDir) {
    const html = (await readSafe(path.join(webDir, "index.html"))) || "";
    const hasEntry = /<script[^>]+src=["'][^"']*\/assets\//i.test(html);
    record("Android build", "shell has entry", hasEntry ? "pass" : "fail",
      hasEntry ? "" : "SPA shell missing script tag");
    const hasHydration =
      /\$_TSR\b/.test(html) ||
      /\$tsr-stream-barrier/.test(html) ||
      /class=["']\$tsr["']/.test(html) ||
      /<div[^>]+id=["']__root["']/i.test(html) ||
      /data-tsr\b/i.test(html) ||
      /window\.__TSR__\s*=/.test(html) ||
      /"dehydratedData"\s*:/.test(html);
    record("Android build", "hydration marker", hasHydration ? "pass" : "fail",
      hasHydration ? "" : "index.html has no $_TSR/__root/data-tsr — router will invariant-throw on device");
  }
}

async function checkCapacitor() {
  const cfg = (await readSafe(path.resolve(ROOT, "capacitor.config.ts"))) || "";
  const m = cfg.match(/webDir\s*:\s*([^,\n}]+)/);
  const configured = m?.[1]?.trim();
  record("Capacitor", "capacitor.config.ts", cfg ? "pass" : "fail", cfg ? "" : "file missing");
  record("Capacitor", "webDir set", configured ? "pass" : "fail",
    configured ? configured : "set webDir in capacitor.config.ts");

  const androidExists = await pathExists(path.resolve(ROOT, "android"));
  record("Capacitor", "android/ exists", androidExists ? "pass" : "warn",
    androidExists ? "" : "run `npx cap add android`");

  if (phase === "post-sync") {
    const copied = await pathExists(path.resolve(ROOT, "android/app/src/main/assets/public/index.html"));
    record("Capacitor", "assets synced", copied ? "pass" : "fail",
      copied ? "" : "run `npx cap sync android`");
  }
}

async function checkNativePlugins() {
  const src = path.resolve(ROOT, "native/android/places/PlacesBridgePlugin.kt");
  const dst = path.resolve(ROOT, "android/app/src/main/java/app/getmindrop/places/PlacesBridgePlugin.kt");
  record("Native plugins", "PlacesBridge source", (await pathExists(src)) ? "pass" : "warn",
    (await pathExists(src)) ? "" : "native/android/places missing");
  record("Native plugins", "PlacesBridge copied", (await pathExists(dst)) ? "pass" : "warn",
    (await pathExists(dst)) ? "" : "run scripts/setup-android-native.sh");

  const mainAct = (await readSafe(path.resolve(ROOT, "android/app/src/main/java/in/mindrop/app/MainActivity.java"))) || "";
  const registered = /registerPlugin\s*\(\s*app\.getmindrop\.places\.PlacesBridgePlugin/.test(mainAct);
  record("Native plugins", "MainActivity registration", registered ? "pass" : "warn",
    registered ? "" : "add registerPlugin(PlacesBridgePlugin.class) in MainActivity onCreate");
}

async function checkManifestAndGradle() {
  const manifest = (await readSafe(path.resolve(ROOT, "android/app/src/main/AndroidManifest.xml"))) || "";
  record("Manifest", "INTERNET perm", /android\.permission\.INTERNET/.test(manifest) ? "pass" : "fail",
    "add <uses-permission android:name=\"android.permission.INTERNET\"/>");
  record("Manifest", "FileProvider", /androidx\.core\.content\.FileProvider/.test(manifest) ? "pass" : "warn", "");

  const appGradle = (await readSafe(path.resolve(ROOT, "android/app/build.gradle"))) || "";
  record("Gradle", "capacitor-android dep", /project\(['"]:capacitor-android['"]\)/.test(appGradle) ? "pass" : "fail",
    "missing capacitor-android in app/build.gradle");
  record("Gradle", "google-services check", /google-services\.json/.test(appGradle) ? "pass" : "warn",
    "google-services plugin block missing");
  const variables = (await readSafe(path.resolve(ROOT, "android/variables.gradle"))) || "";
  record("Gradle", "compileSdk set", /compileSdkVersion\s*=/.test(variables) ? "pass" : "fail", "");

  // ── Kotlin / Capacitor compatibility guard ─────────────────────────
  // Every @capacitor/* plugin's android/build.gradle picks up rootProject.ext.kotlin_version.
  // If the root pins a Kotlin version older than what the plugins were authored
  // against, plugin sources fail with things like "Unresolved reference: padStart".
  // We read the default kotlin_version the installed plugins expect and compare.
  const rootBuild = (await readSafe(path.resolve(ROOT, "android/build.gradle"))) || "";
  const rootKotlin = variables.match(/kotlin_version\s*=\s*['"]([^'"]+)['"]/)?.[1];
  const classpathKotlin = rootBuild.match(/kotlin-gradle-plugin:([^'"\s]+)/)?.[1];
  record("Gradle", "kotlin_version pinned", rootKotlin ? "pass" : "fail",
    rootKotlin || "add kotlin_version to android/variables.gradle");
  record("Gradle", "kotlin classpath matches", rootKotlin && classpathKotlin === rootKotlin ? "pass" : "fail",
    `variables=${rootKotlin} classpath=${classpathKotlin} — must be equal`);

  const pluginDefaults = [];
  const pluginsDir = path.resolve(ROOT, "node_modules/@capacitor");
  if (await pathExists(pluginsDir)) {
    for (const name of await readdir(pluginsDir)) {
      const gradle = await readSafe(path.join(pluginsDir, name, "android/build.gradle"));
      const m = gradle?.match(/kotlin_version[^:]*:\s*['"]([^'"]+)['"]/);
      if (m) pluginDefaults.push({ name, want: m[1] });
    }
  }
  const highest = pluginDefaults.map((p) => p.want).sort().pop();
  const compatible = rootKotlin && highest && cmpVersion(rootKotlin, highest) >= 0;
  record("Gradle", "kotlin ≥ plugin default",
    highest ? (compatible ? "pass" : "fail") : "warn",
    highest
      ? `root=${rootKotlin} plugins want ≥${highest} (${pluginDefaults.map(p=>p.name).join(", ")})`
      : "no @capacitor/* plugins installed");
}

function cmpVersion(a, b) {
  const pa = a.split(".").map((n) => parseInt(n, 10) || 0);
  const pb = b.split(".").map((n) => parseInt(n, 10) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] || 0) - (pb[i] || 0);
    if (d !== 0) return d;
  }
  return 0;
}

async function checkFirebase() {
  const gs = path.resolve(ROOT, "android/app/google-services.json");
  const has = await pathExists(gs);
  record("Firebase", "google-services.json", has ? "pass" : "warn",
    has ? "" : "download from Firebase Console → android/app/google-services.json");
  const pkg = JSON.parse((await readSafe(path.resolve(ROOT, "package.json"))) || "{}");
  const dep = pkg.dependencies?.["@capacitor-firebase/messaging"];
  record("Firebase", "messaging plugin", dep ? "pass" : "warn", dep ? "" : "npm i @capacitor-firebase/messaging");
}

async function checkSupabaseEnv() {
  const envFile = (await readSafe(path.resolve(ROOT, ".env"))) || "";
  const url = process.env.VITE_SUPABASE_URL || (/^VITE_SUPABASE_URL=/m.test(envFile));
  const key = process.env.VITE_SUPABASE_PUBLISHABLE_KEY || (/^VITE_SUPABASE_PUBLISHABLE_KEY=/m.test(envFile));
  record("Supabase", "VITE_SUPABASE_URL", url ? "pass" : "fail", "set in .env");
  record("Supabase", "VITE_SUPABASE_PUBLISHABLE_KEY", key ? "pass" : "fail", "set in .env");
}

function checkToolchain() {
  const node = process.versions.node;
  const nodeMajor = parseInt(node.split(".")[0], 10);
  record("Toolchain", "Node ≥20", nodeMajor >= 20 ? "pass" : "fail", `have ${node}`);

  const npm = spawnSync("npm", ["-v"], { encoding: "utf8", shell: process.platform === "win32" });
  record("Toolchain", "npm", npm.status === 0 ? "pass" : "fail", (npm.stdout || "").trim());

  const javaBin = process.env.JAVA_HOME ? path.join(process.env.JAVA_HOME, "bin/java") : "java";
  const java = spawnSync(javaBin, ["-version"], { encoding: "utf8", shell: process.platform === "win32" });
  const jver = (java.stderr || java.stdout || "").split("\n")[0];
  const jmajor = parseInt((jver.match(/"(\d+)/) || [])[1] || "0", 10);
  record("Toolchain", "JDK ≥17", jmajor >= 17 ? "pass" : "fail", jver || "install JDK 17+");

  const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
  record("Toolchain", "ANDROID_HOME", sdk ? "pass" : "fail", sdk || "install Android Studio & export ANDROID_HOME");

  if (sdk) {
    record("Toolchain", "platform-tools", existsSync(path.join(sdk, "platform-tools")) ? "pass" : "warn", "");
    record("Toolchain", "build-tools", existsSync(path.join(sdk, "build-tools")) ? "pass" : "warn", "");
    record("Toolchain", "sdkmanager", existsSync(path.join(sdk, "cmdline-tools/latest/bin/sdkmanager")) ? "pass" : "warn",
      "install cmdline-tools (latest)");
  }

  const cap = spawnSync("npx", ["--no-install", "cap", "--version"], { encoding: "utf8", shell: process.platform === "win32" });
  record("Toolchain", "Capacitor CLI", cap.status === 0 ? "pass" : "fail", (cap.stdout || "").trim() || "npm install");
}

// ─── Report ─────────────────────────────────────────────────────────────
const ICON = { pass: "✓", warn: "!", fail: "✗" };
const COLOR = { pass: "\x1b[32m", warn: "\x1b[33m", fail: "\x1b[31m", reset: "\x1b[0m" };

function printReport() {
  const grouped = new Map();
  for (const r of results) {
    if (!grouped.has(r.group)) grouped.set(r.group, []);
    grouped.get(r.group).push(r);
  }
  console.log("\n╔══════════════════════════════════════════════════════════════╗");
  console.log("║           MinDrop Android Build Health Dashboard             ║");
  console.log("╚══════════════════════════════════════════════════════════════╝");
  for (const [group, rows] of grouped) {
    console.log(`\n── ${group} ──`);
    for (const r of rows) {
      const color = COLOR[r.status] || "";
      const hint = r.status === "pass" ? "" : (r.hint ? `  ${r.hint}` : "");
      const detail = r.status === "pass" && r.hint ? `  ${r.hint}` : hint;
      console.log(`  ${color}[${ICON[r.status]}]${COLOR.reset} ${r.name.padEnd(28)}${detail}`);
    }
  }
  const fails = results.filter((r) => r.status === "fail").length;
  const warns = results.filter((r) => r.status === "warn").length;
  const passes = results.filter((r) => r.status === "pass").length;
  console.log(`\nSummary: ${passes} pass, ${warns} warn, ${fails} fail\n`);
  return fails;
}

async function checkToolchainMatrix() {
  // Delegates to scripts/validate-toolchain.mjs (single source of truth:
  // scripts/android-toolchain.json, mirrored in docs/ANDROID_TOOLCHAIN.md).
  // Any "fail" here blocks `./rebuild.sh` before `npx cap sync android`.
  const rows = await validateToolchain();
  for (const r of rows) record("Toolchain matrix", r.name, r.status, r.hint);
}

async function main() {
  const out = await checkWebBuild();
  await checkAndroidBuild(out);
  await checkCapacitor();
  await checkNativePlugins();
  await checkManifestAndGradle();
  await checkToolchainMatrix();
  await checkFirebase();
  await checkSupabaseEnv();
  if (isDoctor) checkToolchain();

  const fails = printReport();
  if (reportOnly) process.exit(0);
  if (fails > 0) {
    console.error("✗ Android build blocked. See docs/ANDROID_TOOLCHAIN.md for the supported matrix.");
    process.exit(1);
  }
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
