/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyMindropRouteImport } from './routes/why-mindrop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsFeatureRouteImport } from './routes/settings-feature'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlacesFeatureRouteImport } from './routes/places-feature'
import { Route as NotifyFeatureRouteImport } from './routes/notify-feature'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CtrlVx9k2m7fq3zRouteImport } from './routes/ctrl-vx9k2m7fq3z'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CtrlVx9k2m7fq3zIndexRouteImport } from './routes/ctrl-vx9k2m7fq3z.index'
import { Route as CtrlVx9k2m7fq3zUsersRouteImport } from './routes/ctrl-vx9k2m7fq3z.users'
import { Route as CtrlVx9k2m7fq3zStoryRouteImport } from './routes/ctrl-vx9k2m7fq3z.story'
import { Route as CtrlVx9k2m7fq3zSigninRouteImport } from './routes/ctrl-vx9k2m7fq3z.signin'
import { Route as CtrlVx9k2m7fq3zSettingsRouteImport } from './routes/ctrl-vx9k2m7fq3z.settings'
import { Route as CtrlVx9k2m7fq3zRulesRouteImport } from './routes/ctrl-vx9k2m7fq3z.rules'
import { Route as CtrlVx9k2m7fq3zRecallRouteImport } from './routes/ctrl-vx9k2m7fq3z.recall'
import { Route as CtrlVx9k2m7fq3zQuizRouteImport } from './routes/ctrl-vx9k2m7fq3z.quiz'
import { Route as CtrlVx9k2m7fq3zPricingRouteImport } from './routes/ctrl-vx9k2m7fq3z.pricing'
import { Route as CtrlVx9k2m7fq3zPersonalityRouteImport } from './routes/ctrl-vx9k2m7fq3z.personality'
import { Route as CtrlVx9k2m7fq3zPacksRouteImport } from './routes/ctrl-vx9k2m7fq3z.packs'
import { Route as CtrlVx9k2m7fq3zLimitsRouteImport } from './routes/ctrl-vx9k2m7fq3z.limits'
import { Route as CtrlVx9k2m7fq3zGreetingsRouteImport } from './routes/ctrl-vx9k2m7fq3z.greetings'
import { Route as CtrlVx9k2m7fq3zFlagsRouteImport } from './routes/ctrl-vx9k2m7fq3z.flags'
import { Route as CtrlVx9k2m7fq3zExperimentsRouteImport } from './routes/ctrl-vx9k2m7fq3z.experiments'
import { Route as CtrlVx9k2m7fq3zCountryThemesRouteImport } from './routes/ctrl-vx9k2m7fq3z.country-themes'
import { Route as CtrlVx9k2m7fq3zConfigRouteImport } from './routes/ctrl-vx9k2m7fq3z.config'
import { Route as CtrlVx9k2m7fq3zCategoriesRouteImport } from './routes/ctrl-vx9k2m7fq3z.categories'
import { Route as CtrlVx9k2m7fq3zAuditRouteImport } from './routes/ctrl-vx9k2m7fq3z.audit'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedRecallRouteImport } from './routes/_authenticated/recall'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedPlacesRouteImport } from './routes/_authenticated/places'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedPaywallRouteImport } from './routes/_authenticated/paywall'
import { Route as AuthenticatedPacksPickerRouteImport } from './routes/_authenticated/packs-picker'
import { Route as AuthenticatedPacksRouteImport } from './routes/_authenticated/packs'
import { Route as AuthenticatedNotifyInboxRouteImport } from './routes/_authenticated/notify-inbox'
import { Route as AuthenticatedNotifyRouteImport } from './routes/_authenticated/notify'
import { Route as AuthenticatedErasedRouteImport } from './routes/_authenticated/erased'
import { Route as AuthenticatedDoItLaterRouteImport } from './routes/_authenticated/do-it-later'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedArchivedRouteImport } from './routes/_authenticated/archived'
import { Route as AuthenticatedAlarmSoundRouteImport } from './routes/_authenticated/alarm-sound'
import { Route as CtrlVx9k2m7fq3zPacksIndexRouteImport } from './routes/ctrl-vx9k2m7fq3z.packs.index'
import { Route as AuthenticatedPlacesIndexRouteImport } from './routes/_authenticated/places.index'
import { Route as AuthenticatedPacksIndexRouteImport } from './routes/_authenticated/packs.index'
import { Route as CtrlVx9k2m7fq3zPacksPackIdRouteImport } from './routes/ctrl-vx9k2m7fq3z.packs.$packId'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as AuthenticatedPlacesNewRouteImport } from './routes/_authenticated/places.new'
import { Route as AuthenticatedPlacesPlaceIdRouteImport } from './routes/_authenticated/places.$placeId'
import { Route as AuthenticatedPacksPackIdRouteImport } from './routes/_authenticated/packs.$packId'
import { Route as AuthenticatedMemoryIdRouteImport } from './routes/_authenticated/memory.$id'
import { Route as ApiPublicHooksFireRemindersRouteImport } from './routes/api/public/hooks/fire-reminders'
import { Route as ApiAuthDriveCallbackRouteImport } from './routes/api/auth/drive/callback'
import { Route as AuthenticatedPacksCustomCustomIdRouteImport } from './routes/_authenticated/packs.custom.$customId'

const WhyMindropRoute = WhyMindropRouteImport.update({
  id: '/why-mindrop',
  path: '/why-mindrop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFeatureRoute = SettingsFeatureRouteImport.update({
  id: '/settings-feature',
  path: '/settings-feature',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesFeatureRoute = PlacesFeatureRouteImport.update({
  id: '/places-feature',
  path: '/places-feature',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyFeatureRoute = NotifyFeatureRouteImport.update({
  id: '/notify-feature',
  path: '/notify-feature',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const CtrlVx9k2m7fq3zRoute = CtrlVx9k2m7fq3zRouteImport.update({
  id: '/ctrl-vx9k2m7fq3z',
  path: '/ctrl-vx9k2m7fq3z',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CtrlVx9k2m7fq3zIndexRoute = CtrlVx9k2m7fq3zIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zUsersRoute = CtrlVx9k2m7fq3zUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zStoryRoute = CtrlVx9k2m7fq3zStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zSigninRoute = CtrlVx9k2m7fq3zSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zSettingsRoute = CtrlVx9k2m7fq3zSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zRulesRoute = CtrlVx9k2m7fq3zRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zRecallRoute = CtrlVx9k2m7fq3zRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zQuizRoute = CtrlVx9k2m7fq3zQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zPricingRoute = CtrlVx9k2m7fq3zPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zPersonalityRoute =
  CtrlVx9k2m7fq3zPersonalityRouteImport.update({
    id: '/personality',
    path: '/personality',
    getParentRoute: () => CtrlVx9k2m7fq3zRoute,
  } as any)
const CtrlVx9k2m7fq3zPacksRoute = CtrlVx9k2m7fq3zPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zLimitsRoute = CtrlVx9k2m7fq3zLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zGreetingsRoute =
  CtrlVx9k2m7fq3zGreetingsRouteImport.update({
    id: '/greetings',
    path: '/greetings',
    getParentRoute: () => CtrlVx9k2m7fq3zRoute,
  } as any)
const CtrlVx9k2m7fq3zFlagsRoute = CtrlVx9k2m7fq3zFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zExperimentsRoute =
  CtrlVx9k2m7fq3zExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => CtrlVx9k2m7fq3zRoute,
  } as any)
const CtrlVx9k2m7fq3zCountryThemesRoute =
  CtrlVx9k2m7fq3zCountryThemesRouteImport.update({
    id: '/country-themes',
    path: '/country-themes',
    getParentRoute: () => CtrlVx9k2m7fq3zRoute,
  } as any)
const CtrlVx9k2m7fq3zConfigRoute = CtrlVx9k2m7fq3zConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const CtrlVx9k2m7fq3zCategoriesRoute =
  CtrlVx9k2m7fq3zCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => CtrlVx9k2m7fq3zRoute,
  } as any)
const CtrlVx9k2m7fq3zAuditRoute = CtrlVx9k2m7fq3zAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => CtrlVx9k2m7fq3zRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecallRoute = AuthenticatedRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacesRoute = AuthenticatedPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaywallRoute = AuthenticatedPaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacksPickerRoute =
  AuthenticatedPacksPickerRouteImport.update({
    id: '/packs-picker',
    path: '/packs-picker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacksRoute = AuthenticatedPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotifyInboxRoute =
  AuthenticatedNotifyInboxRouteImport.update({
    id: '/notify-inbox',
    path: '/notify-inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotifyRoute = AuthenticatedNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErasedRoute = AuthenticatedErasedRouteImport.update({
  id: '/erased',
  path: '/erased',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoItLaterRoute = AuthenticatedDoItLaterRouteImport.update({
  id: '/do-it-later',
  path: '/do-it-later',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchivedRoute = AuthenticatedArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlarmSoundRoute = AuthenticatedAlarmSoundRouteImport.update({
  id: '/alarm-sound',
  path: '/alarm-sound',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CtrlVx9k2m7fq3zPacksIndexRoute =
  CtrlVx9k2m7fq3zPacksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CtrlVx9k2m7fq3zPacksRoute,
  } as any)
const AuthenticatedPlacesIndexRoute =
  AuthenticatedPlacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlacesRoute,
  } as any)
const AuthenticatedPacksIndexRoute = AuthenticatedPacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPacksRoute,
} as any)
const CtrlVx9k2m7fq3zPacksPackIdRoute =
  CtrlVx9k2m7fq3zPacksPackIdRouteImport.update({
    id: '/$packId',
    path: '/$packId',
    getParentRoute: () => CtrlVx9k2m7fq3zPacksRoute,
  } as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlacesNewRoute = AuthenticatedPlacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedPlacesRoute,
} as any)
const AuthenticatedPlacesPlaceIdRoute =
  AuthenticatedPlacesPlaceIdRouteImport.update({
    id: '/$placeId',
    path: '/$placeId',
    getParentRoute: () => AuthenticatedPlacesRoute,
  } as any)
const AuthenticatedPacksPackIdRoute =
  AuthenticatedPacksPackIdRouteImport.update({
    id: '/$packId',
    path: '/$packId',
    getParentRoute: () => AuthenticatedPacksRoute,
  } as any)
const AuthenticatedMemoryIdRoute = AuthenticatedMemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksFireRemindersRoute =
  ApiPublicHooksFireRemindersRouteImport.update({
    id: '/api/public/hooks/fire-reminders',
    path: '/api/public/hooks/fire-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDriveCallbackRoute = ApiAuthDriveCallbackRouteImport.update({
  id: '/api/auth/drive/callback',
  path: '/api/auth/drive/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPacksCustomCustomIdRoute =
  AuthenticatedPacksCustomCustomIdRouteImport.update({
    id: '/custom/$customId',
    path: '/custom/$customId',
    getParentRoute: () => AuthenticatedPacksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/ctrl-vx9k2m7fq3z': typeof CtrlVx9k2m7fq3zRouteWithChildren
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/notify-feature': typeof NotifyFeatureRoute
  '/places-feature': typeof PlacesFeatureRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recovery': typeof RecoveryRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings-feature': typeof SettingsFeatureRoute
  '/signin': typeof SigninRoute
  '/splash': typeof SplashRoute
  '/terms': typeof TermsRoute
  '/why-mindrop': typeof WhyMindropRoute
  '/alarm-sound': typeof AuthenticatedAlarmSoundRoute
  '/archived': typeof AuthenticatedArchivedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/do-it-later': typeof AuthenticatedDoItLaterRoute
  '/erased': typeof AuthenticatedErasedRoute
  '/notify': typeof AuthenticatedNotifyRoute
  '/notify-inbox': typeof AuthenticatedNotifyInboxRoute
  '/packs': typeof AuthenticatedPacksRouteWithChildren
  '/packs-picker': typeof AuthenticatedPacksPickerRoute
  '/paywall': typeof AuthenticatedPaywallRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/places': typeof AuthenticatedPlacesRouteWithChildren
  '/quiz': typeof AuthenticatedQuizRoute
  '/recall': typeof AuthenticatedRecallRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ctrl-vx9k2m7fq3z/audit': typeof CtrlVx9k2m7fq3zAuditRoute
  '/ctrl-vx9k2m7fq3z/categories': typeof CtrlVx9k2m7fq3zCategoriesRoute
  '/ctrl-vx9k2m7fq3z/config': typeof CtrlVx9k2m7fq3zConfigRoute
  '/ctrl-vx9k2m7fq3z/country-themes': typeof CtrlVx9k2m7fq3zCountryThemesRoute
  '/ctrl-vx9k2m7fq3z/experiments': typeof CtrlVx9k2m7fq3zExperimentsRoute
  '/ctrl-vx9k2m7fq3z/flags': typeof CtrlVx9k2m7fq3zFlagsRoute
  '/ctrl-vx9k2m7fq3z/greetings': typeof CtrlVx9k2m7fq3zGreetingsRoute
  '/ctrl-vx9k2m7fq3z/limits': typeof CtrlVx9k2m7fq3zLimitsRoute
  '/ctrl-vx9k2m7fq3z/packs': typeof CtrlVx9k2m7fq3zPacksRouteWithChildren
  '/ctrl-vx9k2m7fq3z/personality': typeof CtrlVx9k2m7fq3zPersonalityRoute
  '/ctrl-vx9k2m7fq3z/pricing': typeof CtrlVx9k2m7fq3zPricingRoute
  '/ctrl-vx9k2m7fq3z/quiz': typeof CtrlVx9k2m7fq3zQuizRoute
  '/ctrl-vx9k2m7fq3z/recall': typeof CtrlVx9k2m7fq3zRecallRoute
  '/ctrl-vx9k2m7fq3z/rules': typeof CtrlVx9k2m7fq3zRulesRoute
  '/ctrl-vx9k2m7fq3z/settings': typeof CtrlVx9k2m7fq3zSettingsRoute
  '/ctrl-vx9k2m7fq3z/signin': typeof CtrlVx9k2m7fq3zSigninRoute
  '/ctrl-vx9k2m7fq3z/story': typeof CtrlVx9k2m7fq3zStoryRoute
  '/ctrl-vx9k2m7fq3z/users': typeof CtrlVx9k2m7fq3zUsersRoute
  '/ctrl-vx9k2m7fq3z/': typeof CtrlVx9k2m7fq3zIndexRoute
  '/memory/$id': typeof AuthenticatedMemoryIdRoute
  '/packs/$packId': typeof AuthenticatedPacksPackIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/places/new': typeof AuthenticatedPlacesNewRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/ctrl-vx9k2m7fq3z/packs/$packId': typeof CtrlVx9k2m7fq3zPacksPackIdRoute
  '/packs/': typeof AuthenticatedPacksIndexRoute
  '/places/': typeof AuthenticatedPlacesIndexRoute
  '/ctrl-vx9k2m7fq3z/packs/': typeof CtrlVx9k2m7fq3zPacksIndexRoute
  '/packs/custom/$customId': typeof AuthenticatedPacksCustomCustomIdRoute
  '/api/auth/drive/callback': typeof ApiAuthDriveCallbackRoute
  '/api/public/hooks/fire-reminders': typeof ApiPublicHooksFireRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/notify-feature': typeof NotifyFeatureRoute
  '/places-feature': typeof PlacesFeatureRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recovery': typeof RecoveryRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings-feature': typeof SettingsFeatureRoute
  '/signin': typeof SigninRoute
  '/splash': typeof SplashRoute
  '/terms': typeof TermsRoute
  '/why-mindrop': typeof WhyMindropRoute
  '/alarm-sound': typeof AuthenticatedAlarmSoundRoute
  '/archived': typeof AuthenticatedArchivedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/do-it-later': typeof AuthenticatedDoItLaterRoute
  '/erased': typeof AuthenticatedErasedRoute
  '/notify': typeof AuthenticatedNotifyRoute
  '/notify-inbox': typeof AuthenticatedNotifyInboxRoute
  '/packs-picker': typeof AuthenticatedPacksPickerRoute
  '/paywall': typeof AuthenticatedPaywallRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/recall': typeof AuthenticatedRecallRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ctrl-vx9k2m7fq3z/audit': typeof CtrlVx9k2m7fq3zAuditRoute
  '/ctrl-vx9k2m7fq3z/categories': typeof CtrlVx9k2m7fq3zCategoriesRoute
  '/ctrl-vx9k2m7fq3z/config': typeof CtrlVx9k2m7fq3zConfigRoute
  '/ctrl-vx9k2m7fq3z/country-themes': typeof CtrlVx9k2m7fq3zCountryThemesRoute
  '/ctrl-vx9k2m7fq3z/experiments': typeof CtrlVx9k2m7fq3zExperimentsRoute
  '/ctrl-vx9k2m7fq3z/flags': typeof CtrlVx9k2m7fq3zFlagsRoute
  '/ctrl-vx9k2m7fq3z/greetings': typeof CtrlVx9k2m7fq3zGreetingsRoute
  '/ctrl-vx9k2m7fq3z/limits': typeof CtrlVx9k2m7fq3zLimitsRoute
  '/ctrl-vx9k2m7fq3z/personality': typeof CtrlVx9k2m7fq3zPersonalityRoute
  '/ctrl-vx9k2m7fq3z/pricing': typeof CtrlVx9k2m7fq3zPricingRoute
  '/ctrl-vx9k2m7fq3z/quiz': typeof CtrlVx9k2m7fq3zQuizRoute
  '/ctrl-vx9k2m7fq3z/recall': typeof CtrlVx9k2m7fq3zRecallRoute
  '/ctrl-vx9k2m7fq3z/rules': typeof CtrlVx9k2m7fq3zRulesRoute
  '/ctrl-vx9k2m7fq3z/settings': typeof CtrlVx9k2m7fq3zSettingsRoute
  '/ctrl-vx9k2m7fq3z/signin': typeof CtrlVx9k2m7fq3zSigninRoute
  '/ctrl-vx9k2m7fq3z/story': typeof CtrlVx9k2m7fq3zStoryRoute
  '/ctrl-vx9k2m7fq3z/users': typeof CtrlVx9k2m7fq3zUsersRoute
  '/ctrl-vx9k2m7fq3z': typeof CtrlVx9k2m7fq3zIndexRoute
  '/memory/$id': typeof AuthenticatedMemoryIdRoute
  '/packs/$packId': typeof AuthenticatedPacksPackIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/places/new': typeof AuthenticatedPlacesNewRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/ctrl-vx9k2m7fq3z/packs/$packId': typeof CtrlVx9k2m7fq3zPacksPackIdRoute
  '/packs': typeof AuthenticatedPacksIndexRoute
  '/places': typeof AuthenticatedPlacesIndexRoute
  '/ctrl-vx9k2m7fq3z/packs': typeof CtrlVx9k2m7fq3zPacksIndexRoute
  '/packs/custom/$customId': typeof AuthenticatedPacksCustomCustomIdRoute
  '/api/auth/drive/callback': typeof ApiAuthDriveCallbackRoute
  '/api/public/hooks/fire-reminders': typeof ApiPublicHooksFireRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/ctrl-vx9k2m7fq3z': typeof CtrlVx9k2m7fq3zRouteWithChildren
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/notify-feature': typeof NotifyFeatureRoute
  '/places-feature': typeof PlacesFeatureRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recovery': typeof RecoveryRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings-feature': typeof SettingsFeatureRoute
  '/signin': typeof SigninRoute
  '/splash': typeof SplashRoute
  '/terms': typeof TermsRoute
  '/why-mindrop': typeof WhyMindropRoute
  '/_authenticated/alarm-sound': typeof AuthenticatedAlarmSoundRoute
  '/_authenticated/archived': typeof AuthenticatedArchivedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/do-it-later': typeof AuthenticatedDoItLaterRoute
  '/_authenticated/erased': typeof AuthenticatedErasedRoute
  '/_authenticated/notify': typeof AuthenticatedNotifyRoute
  '/_authenticated/notify-inbox': typeof AuthenticatedNotifyInboxRoute
  '/_authenticated/packs': typeof AuthenticatedPacksRouteWithChildren
  '/_authenticated/packs-picker': typeof AuthenticatedPacksPickerRoute
  '/_authenticated/paywall': typeof AuthenticatedPaywallRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/places': typeof AuthenticatedPlacesRouteWithChildren
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/recall': typeof AuthenticatedRecallRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ctrl-vx9k2m7fq3z/audit': typeof CtrlVx9k2m7fq3zAuditRoute
  '/ctrl-vx9k2m7fq3z/categories': typeof CtrlVx9k2m7fq3zCategoriesRoute
  '/ctrl-vx9k2m7fq3z/config': typeof CtrlVx9k2m7fq3zConfigRoute
  '/ctrl-vx9k2m7fq3z/country-themes': typeof CtrlVx9k2m7fq3zCountryThemesRoute
  '/ctrl-vx9k2m7fq3z/experiments': typeof CtrlVx9k2m7fq3zExperimentsRoute
  '/ctrl-vx9k2m7fq3z/flags': typeof CtrlVx9k2m7fq3zFlagsRoute
  '/ctrl-vx9k2m7fq3z/greetings': typeof CtrlVx9k2m7fq3zGreetingsRoute
  '/ctrl-vx9k2m7fq3z/limits': typeof CtrlVx9k2m7fq3zLimitsRoute
  '/ctrl-vx9k2m7fq3z/packs': typeof CtrlVx9k2m7fq3zPacksRouteWithChildren
  '/ctrl-vx9k2m7fq3z/personality': typeof CtrlVx9k2m7fq3zPersonalityRoute
  '/ctrl-vx9k2m7fq3z/pricing': typeof CtrlVx9k2m7fq3zPricingRoute
  '/ctrl-vx9k2m7fq3z/quiz': typeof CtrlVx9k2m7fq3zQuizRoute
  '/ctrl-vx9k2m7fq3z/recall': typeof CtrlVx9k2m7fq3zRecallRoute
  '/ctrl-vx9k2m7fq3z/rules': typeof CtrlVx9k2m7fq3zRulesRoute
  '/ctrl-vx9k2m7fq3z/settings': typeof CtrlVx9k2m7fq3zSettingsRoute
  '/ctrl-vx9k2m7fq3z/signin': typeof CtrlVx9k2m7fq3zSigninRoute
  '/ctrl-vx9k2m7fq3z/story': typeof CtrlVx9k2m7fq3zStoryRoute
  '/ctrl-vx9k2m7fq3z/users': typeof CtrlVx9k2m7fq3zUsersRoute
  '/ctrl-vx9k2m7fq3z/': typeof CtrlVx9k2m7fq3zIndexRoute
  '/_authenticated/memory/$id': typeof AuthenticatedMemoryIdRoute
  '/_authenticated/packs/$packId': typeof AuthenticatedPacksPackIdRoute
  '/_authenticated/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/_authenticated/places/new': typeof AuthenticatedPlacesNewRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/ctrl-vx9k2m7fq3z/packs/$packId': typeof CtrlVx9k2m7fq3zPacksPackIdRoute
  '/_authenticated/packs/': typeof AuthenticatedPacksIndexRoute
  '/_authenticated/places/': typeof AuthenticatedPlacesIndexRoute
  '/ctrl-vx9k2m7fq3z/packs/': typeof CtrlVx9k2m7fq3zPacksIndexRoute
  '/_authenticated/packs/custom/$customId': typeof AuthenticatedPacksCustomCustomIdRoute
  '/api/auth/drive/callback': typeof ApiAuthDriveCallbackRoute
  '/api/public/hooks/fire-reminders': typeof ApiPublicHooksFireRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/ctrl-vx9k2m7fq3z'
    | '/download'
    | '/faq'
    | '/features'
    | '/home'
    | '/how-it-works'
    | '/notify-feature'
    | '/places-feature'
    | '/pricing'
    | '/privacy'
    | '/recovery'
    | '/refunds'
    | '/reset-password'
    | '/settings-feature'
    | '/signin'
    | '/splash'
    | '/terms'
    | '/why-mindrop'
    | '/alarm-sound'
    | '/archived'
    | '/dashboard'
    | '/diagnostics'
    | '/do-it-later'
    | '/erased'
    | '/notify'
    | '/notify-inbox'
    | '/packs'
    | '/packs-picker'
    | '/paywall'
    | '/permissions'
    | '/places'
    | '/quiz'
    | '/recall'
    | '/rules'
    | '/settings'
    | '/auth/callback'
    | '/ctrl-vx9k2m7fq3z/audit'
    | '/ctrl-vx9k2m7fq3z/categories'
    | '/ctrl-vx9k2m7fq3z/config'
    | '/ctrl-vx9k2m7fq3z/country-themes'
    | '/ctrl-vx9k2m7fq3z/experiments'
    | '/ctrl-vx9k2m7fq3z/flags'
    | '/ctrl-vx9k2m7fq3z/greetings'
    | '/ctrl-vx9k2m7fq3z/limits'
    | '/ctrl-vx9k2m7fq3z/packs'
    | '/ctrl-vx9k2m7fq3z/personality'
    | '/ctrl-vx9k2m7fq3z/pricing'
    | '/ctrl-vx9k2m7fq3z/quiz'
    | '/ctrl-vx9k2m7fq3z/recall'
    | '/ctrl-vx9k2m7fq3z/rules'
    | '/ctrl-vx9k2m7fq3z/settings'
    | '/ctrl-vx9k2m7fq3z/signin'
    | '/ctrl-vx9k2m7fq3z/story'
    | '/ctrl-vx9k2m7fq3z/users'
    | '/ctrl-vx9k2m7fq3z/'
    | '/memory/$id'
    | '/packs/$packId'
    | '/places/$placeId'
    | '/places/new'
    | '/api/public/cashfree-webhook'
    | '/ctrl-vx9k2m7fq3z/packs/$packId'
    | '/packs/'
    | '/places/'
    | '/ctrl-vx9k2m7fq3z/packs/'
    | '/packs/custom/$customId'
    | '/api/auth/drive/callback'
    | '/api/public/hooks/fire-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/download'
    | '/faq'
    | '/features'
    | '/home'
    | '/how-it-works'
    | '/notify-feature'
    | '/places-feature'
    | '/pricing'
    | '/privacy'
    | '/recovery'
    | '/refunds'
    | '/reset-password'
    | '/settings-feature'
    | '/signin'
    | '/splash'
    | '/terms'
    | '/why-mindrop'
    | '/alarm-sound'
    | '/archived'
    | '/dashboard'
    | '/diagnostics'
    | '/do-it-later'
    | '/erased'
    | '/notify'
    | '/notify-inbox'
    | '/packs-picker'
    | '/paywall'
    | '/permissions'
    | '/quiz'
    | '/recall'
    | '/rules'
    | '/settings'
    | '/auth/callback'
    | '/ctrl-vx9k2m7fq3z/audit'
    | '/ctrl-vx9k2m7fq3z/categories'
    | '/ctrl-vx9k2m7fq3z/config'
    | '/ctrl-vx9k2m7fq3z/country-themes'
    | '/ctrl-vx9k2m7fq3z/experiments'
    | '/ctrl-vx9k2m7fq3z/flags'
    | '/ctrl-vx9k2m7fq3z/greetings'
    | '/ctrl-vx9k2m7fq3z/limits'
    | '/ctrl-vx9k2m7fq3z/personality'
    | '/ctrl-vx9k2m7fq3z/pricing'
    | '/ctrl-vx9k2m7fq3z/quiz'
    | '/ctrl-vx9k2m7fq3z/recall'
    | '/ctrl-vx9k2m7fq3z/rules'
    | '/ctrl-vx9k2m7fq3z/settings'
    | '/ctrl-vx9k2m7fq3z/signin'
    | '/ctrl-vx9k2m7fq3z/story'
    | '/ctrl-vx9k2m7fq3z/users'
    | '/ctrl-vx9k2m7fq3z'
    | '/memory/$id'
    | '/packs/$packId'
    | '/places/$placeId'
    | '/places/new'
    | '/api/public/cashfree-webhook'
    | '/ctrl-vx9k2m7fq3z/packs/$packId'
    | '/packs'
    | '/places'
    | '/ctrl-vx9k2m7fq3z/packs'
    | '/packs/custom/$customId'
    | '/api/auth/drive/callback'
    | '/api/public/hooks/fire-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/ctrl-vx9k2m7fq3z'
    | '/download'
    | '/faq'
    | '/features'
    | '/home'
    | '/how-it-works'
    | '/notify-feature'
    | '/places-feature'
    | '/pricing'
    | '/privacy'
    | '/recovery'
    | '/refunds'
    | '/reset-password'
    | '/settings-feature'
    | '/signin'
    | '/splash'
    | '/terms'
    | '/why-mindrop'
    | '/_authenticated/alarm-sound'
    | '/_authenticated/archived'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostics'
    | '/_authenticated/do-it-later'
    | '/_authenticated/erased'
    | '/_authenticated/notify'
    | '/_authenticated/notify-inbox'
    | '/_authenticated/packs'
    | '/_authenticated/packs-picker'
    | '/_authenticated/paywall'
    | '/_authenticated/permissions'
    | '/_authenticated/places'
    | '/_authenticated/quiz'
    | '/_authenticated/recall'
    | '/_authenticated/rules'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/ctrl-vx9k2m7fq3z/audit'
    | '/ctrl-vx9k2m7fq3z/categories'
    | '/ctrl-vx9k2m7fq3z/config'
    | '/ctrl-vx9k2m7fq3z/country-themes'
    | '/ctrl-vx9k2m7fq3z/experiments'
    | '/ctrl-vx9k2m7fq3z/flags'
    | '/ctrl-vx9k2m7fq3z/greetings'
    | '/ctrl-vx9k2m7fq3z/limits'
    | '/ctrl-vx9k2m7fq3z/packs'
    | '/ctrl-vx9k2m7fq3z/personality'
    | '/ctrl-vx9k2m7fq3z/pricing'
    | '/ctrl-vx9k2m7fq3z/quiz'
    | '/ctrl-vx9k2m7fq3z/recall'
    | '/ctrl-vx9k2m7fq3z/rules'
    | '/ctrl-vx9k2m7fq3z/settings'
    | '/ctrl-vx9k2m7fq3z/signin'
    | '/ctrl-vx9k2m7fq3z/story'
    | '/ctrl-vx9k2m7fq3z/users'
    | '/ctrl-vx9k2m7fq3z/'
    | '/_authenticated/memory/$id'
    | '/_authenticated/packs/$packId'
    | '/_authenticated/places/$placeId'
    | '/_authenticated/places/new'
    | '/api/public/cashfree-webhook'
    | '/ctrl-vx9k2m7fq3z/packs/$packId'
    | '/_authenticated/packs/'
    | '/_authenticated/places/'
    | '/ctrl-vx9k2m7fq3z/packs/'
    | '/_authenticated/packs/custom/$customId'
    | '/api/auth/drive/callback'
    | '/api/public/hooks/fire-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  CtrlVx9k2m7fq3zRoute: typeof CtrlVx9k2m7fq3zRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NotifyFeatureRoute: typeof NotifyFeatureRoute
  PlacesFeatureRoute: typeof PlacesFeatureRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoveryRoute: typeof RecoveryRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsFeatureRoute: typeof SettingsFeatureRoute
  SigninRoute: typeof SigninRoute
  SplashRoute: typeof SplashRoute
  TermsRoute: typeof TermsRoute
  WhyMindropRoute: typeof WhyMindropRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  ApiAuthDriveCallbackRoute: typeof ApiAuthDriveCallbackRoute
  ApiPublicHooksFireRemindersRoute: typeof ApiPublicHooksFireRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-mindrop': {
      id: '/why-mindrop'
      path: '/why-mindrop'
      fullPath: '/why-mindrop'
      preLoaderRoute: typeof WhyMindropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-feature': {
      id: '/settings-feature'
      path: '/settings-feature'
      fullPath: '/settings-feature'
      preLoaderRoute: typeof SettingsFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places-feature': {
      id: '/places-feature'
      path: '/places-feature'
      fullPath: '/places-feature'
      preLoaderRoute: typeof PlacesFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify-feature': {
      id: '/notify-feature'
      path: '/notify-feature'
      fullPath: '/notify-feature'
      preLoaderRoute: typeof NotifyFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ctrl-vx9k2m7fq3z': {
      id: '/ctrl-vx9k2m7fq3z'
      path: '/ctrl-vx9k2m7fq3z'
      fullPath: '/ctrl-vx9k2m7fq3z'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ctrl-vx9k2m7fq3z/': {
      id: '/ctrl-vx9k2m7fq3z/'
      path: '/'
      fullPath: '/ctrl-vx9k2m7fq3z/'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zIndexRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/users': {
      id: '/ctrl-vx9k2m7fq3z/users'
      path: '/users'
      fullPath: '/ctrl-vx9k2m7fq3z/users'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zUsersRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/story': {
      id: '/ctrl-vx9k2m7fq3z/story'
      path: '/story'
      fullPath: '/ctrl-vx9k2m7fq3z/story'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zStoryRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/signin': {
      id: '/ctrl-vx9k2m7fq3z/signin'
      path: '/signin'
      fullPath: '/ctrl-vx9k2m7fq3z/signin'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zSigninRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/settings': {
      id: '/ctrl-vx9k2m7fq3z/settings'
      path: '/settings'
      fullPath: '/ctrl-vx9k2m7fq3z/settings'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zSettingsRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/rules': {
      id: '/ctrl-vx9k2m7fq3z/rules'
      path: '/rules'
      fullPath: '/ctrl-vx9k2m7fq3z/rules'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zRulesRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/recall': {
      id: '/ctrl-vx9k2m7fq3z/recall'
      path: '/recall'
      fullPath: '/ctrl-vx9k2m7fq3z/recall'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zRecallRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/quiz': {
      id: '/ctrl-vx9k2m7fq3z/quiz'
      path: '/quiz'
      fullPath: '/ctrl-vx9k2m7fq3z/quiz'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zQuizRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/pricing': {
      id: '/ctrl-vx9k2m7fq3z/pricing'
      path: '/pricing'
      fullPath: '/ctrl-vx9k2m7fq3z/pricing'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zPricingRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/personality': {
      id: '/ctrl-vx9k2m7fq3z/personality'
      path: '/personality'
      fullPath: '/ctrl-vx9k2m7fq3z/personality'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zPersonalityRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/packs': {
      id: '/ctrl-vx9k2m7fq3z/packs'
      path: '/packs'
      fullPath: '/ctrl-vx9k2m7fq3z/packs'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zPacksRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/limits': {
      id: '/ctrl-vx9k2m7fq3z/limits'
      path: '/limits'
      fullPath: '/ctrl-vx9k2m7fq3z/limits'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zLimitsRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/greetings': {
      id: '/ctrl-vx9k2m7fq3z/greetings'
      path: '/greetings'
      fullPath: '/ctrl-vx9k2m7fq3z/greetings'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zGreetingsRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/flags': {
      id: '/ctrl-vx9k2m7fq3z/flags'
      path: '/flags'
      fullPath: '/ctrl-vx9k2m7fq3z/flags'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zFlagsRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/experiments': {
      id: '/ctrl-vx9k2m7fq3z/experiments'
      path: '/experiments'
      fullPath: '/ctrl-vx9k2m7fq3z/experiments'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zExperimentsRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/country-themes': {
      id: '/ctrl-vx9k2m7fq3z/country-themes'
      path: '/country-themes'
      fullPath: '/ctrl-vx9k2m7fq3z/country-themes'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zCountryThemesRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/config': {
      id: '/ctrl-vx9k2m7fq3z/config'
      path: '/config'
      fullPath: '/ctrl-vx9k2m7fq3z/config'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zConfigRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/categories': {
      id: '/ctrl-vx9k2m7fq3z/categories'
      path: '/categories'
      fullPath: '/ctrl-vx9k2m7fq3z/categories'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zCategoriesRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/ctrl-vx9k2m7fq3z/audit': {
      id: '/ctrl-vx9k2m7fq3z/audit'
      path: '/audit'
      fullPath: '/ctrl-vx9k2m7fq3z/audit'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zAuditRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recall': {
      id: '/_authenticated/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof AuthenticatedRecallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places': {
      id: '/_authenticated/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AuthenticatedPlacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paywall': {
      id: '/_authenticated/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof AuthenticatedPaywallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packs-picker': {
      id: '/_authenticated/packs-picker'
      path: '/packs-picker'
      fullPath: '/packs-picker'
      preLoaderRoute: typeof AuthenticatedPacksPickerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packs': {
      id: '/_authenticated/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof AuthenticatedPacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notify-inbox': {
      id: '/_authenticated/notify-inbox'
      path: '/notify-inbox'
      fullPath: '/notify-inbox'
      preLoaderRoute: typeof AuthenticatedNotifyInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notify': {
      id: '/_authenticated/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof AuthenticatedNotifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/erased': {
      id: '/_authenticated/erased'
      path: '/erased'
      fullPath: '/erased'
      preLoaderRoute: typeof AuthenticatedErasedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/do-it-later': {
      id: '/_authenticated/do-it-later'
      path: '/do-it-later'
      fullPath: '/do-it-later'
      preLoaderRoute: typeof AuthenticatedDoItLaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archived': {
      id: '/_authenticated/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof AuthenticatedArchivedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alarm-sound': {
      id: '/_authenticated/alarm-sound'
      path: '/alarm-sound'
      fullPath: '/alarm-sound'
      preLoaderRoute: typeof AuthenticatedAlarmSoundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ctrl-vx9k2m7fq3z/packs/': {
      id: '/ctrl-vx9k2m7fq3z/packs/'
      path: '/'
      fullPath: '/ctrl-vx9k2m7fq3z/packs/'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zPacksIndexRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zPacksRoute
    }
    '/_authenticated/places/': {
      id: '/_authenticated/places/'
      path: '/'
      fullPath: '/places/'
      preLoaderRoute: typeof AuthenticatedPlacesIndexRouteImport
      parentRoute: typeof AuthenticatedPlacesRoute
    }
    '/_authenticated/packs/': {
      id: '/_authenticated/packs/'
      path: '/'
      fullPath: '/packs/'
      preLoaderRoute: typeof AuthenticatedPacksIndexRouteImport
      parentRoute: typeof AuthenticatedPacksRoute
    }
    '/ctrl-vx9k2m7fq3z/packs/$packId': {
      id: '/ctrl-vx9k2m7fq3z/packs/$packId'
      path: '/$packId'
      fullPath: '/ctrl-vx9k2m7fq3z/packs/$packId'
      preLoaderRoute: typeof CtrlVx9k2m7fq3zPacksPackIdRouteImport
      parentRoute: typeof CtrlVx9k2m7fq3zPacksRoute
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/places/new': {
      id: '/_authenticated/places/new'
      path: '/new'
      fullPath: '/places/new'
      preLoaderRoute: typeof AuthenticatedPlacesNewRouteImport
      parentRoute: typeof AuthenticatedPlacesRoute
    }
    '/_authenticated/places/$placeId': {
      id: '/_authenticated/places/$placeId'
      path: '/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof AuthenticatedPlacesPlaceIdRouteImport
      parentRoute: typeof AuthenticatedPlacesRoute
    }
    '/_authenticated/packs/$packId': {
      id: '/_authenticated/packs/$packId'
      path: '/$packId'
      fullPath: '/packs/$packId'
      preLoaderRoute: typeof AuthenticatedPacksPackIdRouteImport
      parentRoute: typeof AuthenticatedPacksRoute
    }
    '/_authenticated/memory/$id': {
      id: '/_authenticated/memory/$id'
      path: '/memory/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof AuthenticatedMemoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/fire-reminders': {
      id: '/api/public/hooks/fire-reminders'
      path: '/api/public/hooks/fire-reminders'
      fullPath: '/api/public/hooks/fire-reminders'
      preLoaderRoute: typeof ApiPublicHooksFireRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/drive/callback': {
      id: '/api/auth/drive/callback'
      path: '/api/auth/drive/callback'
      fullPath: '/api/auth/drive/callback'
      preLoaderRoute: typeof ApiAuthDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/packs/custom/$customId': {
      id: '/_authenticated/packs/custom/$customId'
      path: '/custom/$customId'
      fullPath: '/packs/custom/$customId'
      preLoaderRoute: typeof AuthenticatedPacksCustomCustomIdRouteImport
      parentRoute: typeof AuthenticatedPacksRoute
    }
  }
}

interface AuthenticatedPacksRouteChildren {
  AuthenticatedPacksPackIdRoute: typeof AuthenticatedPacksPackIdRoute
  AuthenticatedPacksIndexRoute: typeof AuthenticatedPacksIndexRoute
  AuthenticatedPacksCustomCustomIdRoute: typeof AuthenticatedPacksCustomCustomIdRoute
}

const AuthenticatedPacksRouteChildren: AuthenticatedPacksRouteChildren = {
  AuthenticatedPacksPackIdRoute: AuthenticatedPacksPackIdRoute,
  AuthenticatedPacksIndexRoute: AuthenticatedPacksIndexRoute,
  AuthenticatedPacksCustomCustomIdRoute: AuthenticatedPacksCustomCustomIdRoute,
}

const AuthenticatedPacksRouteWithChildren =
  AuthenticatedPacksRoute._addFileChildren(AuthenticatedPacksRouteChildren)

interface AuthenticatedPlacesRouteChildren {
  AuthenticatedPlacesPlaceIdRoute: typeof AuthenticatedPlacesPlaceIdRoute
  AuthenticatedPlacesNewRoute: typeof AuthenticatedPlacesNewRoute
  AuthenticatedPlacesIndexRoute: typeof AuthenticatedPlacesIndexRoute
}

const AuthenticatedPlacesRouteChildren: AuthenticatedPlacesRouteChildren = {
  AuthenticatedPlacesPlaceIdRoute: AuthenticatedPlacesPlaceIdRoute,
  AuthenticatedPlacesNewRoute: AuthenticatedPlacesNewRoute,
  AuthenticatedPlacesIndexRoute: AuthenticatedPlacesIndexRoute,
}

const AuthenticatedPlacesRouteWithChildren =
  AuthenticatedPlacesRoute._addFileChildren(AuthenticatedPlacesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlarmSoundRoute: typeof AuthenticatedAlarmSoundRoute
  AuthenticatedArchivedRoute: typeof AuthenticatedArchivedRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedDoItLaterRoute: typeof AuthenticatedDoItLaterRoute
  AuthenticatedErasedRoute: typeof AuthenticatedErasedRoute
  AuthenticatedNotifyRoute: typeof AuthenticatedNotifyRoute
  AuthenticatedNotifyInboxRoute: typeof AuthenticatedNotifyInboxRoute
  AuthenticatedPacksRoute: typeof AuthenticatedPacksRouteWithChildren
  AuthenticatedPacksPickerRoute: typeof AuthenticatedPacksPickerRoute
  AuthenticatedPaywallRoute: typeof AuthenticatedPaywallRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPlacesRoute: typeof AuthenticatedPlacesRouteWithChildren
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedRecallRoute: typeof AuthenticatedRecallRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMemoryIdRoute: typeof AuthenticatedMemoryIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlarmSoundRoute: AuthenticatedAlarmSoundRoute,
  AuthenticatedArchivedRoute: AuthenticatedArchivedRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedDoItLaterRoute: AuthenticatedDoItLaterRoute,
  AuthenticatedErasedRoute: AuthenticatedErasedRoute,
  AuthenticatedNotifyRoute: AuthenticatedNotifyRoute,
  AuthenticatedNotifyInboxRoute: AuthenticatedNotifyInboxRoute,
  AuthenticatedPacksRoute: AuthenticatedPacksRouteWithChildren,
  AuthenticatedPacksPickerRoute: AuthenticatedPacksPickerRoute,
  AuthenticatedPaywallRoute: AuthenticatedPaywallRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPlacesRoute: AuthenticatedPlacesRouteWithChildren,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedRecallRoute: AuthenticatedRecallRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMemoryIdRoute: AuthenticatedMemoryIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CtrlVx9k2m7fq3zPacksRouteChildren {
  CtrlVx9k2m7fq3zPacksPackIdRoute: typeof CtrlVx9k2m7fq3zPacksPackIdRoute
  CtrlVx9k2m7fq3zPacksIndexRoute: typeof CtrlVx9k2m7fq3zPacksIndexRoute
}

const CtrlVx9k2m7fq3zPacksRouteChildren: CtrlVx9k2m7fq3zPacksRouteChildren = {
  CtrlVx9k2m7fq3zPacksPackIdRoute: CtrlVx9k2m7fq3zPacksPackIdRoute,
  CtrlVx9k2m7fq3zPacksIndexRoute: CtrlVx9k2m7fq3zPacksIndexRoute,
}

const CtrlVx9k2m7fq3zPacksRouteWithChildren =
  CtrlVx9k2m7fq3zPacksRoute._addFileChildren(CtrlVx9k2m7fq3zPacksRouteChildren)

interface CtrlVx9k2m7fq3zRouteChildren {
  CtrlVx9k2m7fq3zAuditRoute: typeof CtrlVx9k2m7fq3zAuditRoute
  CtrlVx9k2m7fq3zCategoriesRoute: typeof CtrlVx9k2m7fq3zCategoriesRoute
  CtrlVx9k2m7fq3zConfigRoute: typeof CtrlVx9k2m7fq3zConfigRoute
  CtrlVx9k2m7fq3zCountryThemesRoute: typeof CtrlVx9k2m7fq3zCountryThemesRoute
  CtrlVx9k2m7fq3zExperimentsRoute: typeof CtrlVx9k2m7fq3zExperimentsRoute
  CtrlVx9k2m7fq3zFlagsRoute: typeof CtrlVx9k2m7fq3zFlagsRoute
  CtrlVx9k2m7fq3zGreetingsRoute: typeof CtrlVx9k2m7fq3zGreetingsRoute
  CtrlVx9k2m7fq3zLimitsRoute: typeof CtrlVx9k2m7fq3zLimitsRoute
  CtrlVx9k2m7fq3zPacksRoute: typeof CtrlVx9k2m7fq3zPacksRouteWithChildren
  CtrlVx9k2m7fq3zPersonalityRoute: typeof CtrlVx9k2m7fq3zPersonalityRoute
  CtrlVx9k2m7fq3zPricingRoute: typeof CtrlVx9k2m7fq3zPricingRoute
  CtrlVx9k2m7fq3zQuizRoute: typeof CtrlVx9k2m7fq3zQuizRoute
  CtrlVx9k2m7fq3zRecallRoute: typeof CtrlVx9k2m7fq3zRecallRoute
  CtrlVx9k2m7fq3zRulesRoute: typeof CtrlVx9k2m7fq3zRulesRoute
  CtrlVx9k2m7fq3zSettingsRoute: typeof CtrlVx9k2m7fq3zSettingsRoute
  CtrlVx9k2m7fq3zSigninRoute: typeof CtrlVx9k2m7fq3zSigninRoute
  CtrlVx9k2m7fq3zStoryRoute: typeof CtrlVx9k2m7fq3zStoryRoute
  CtrlVx9k2m7fq3zUsersRoute: typeof CtrlVx9k2m7fq3zUsersRoute
  CtrlVx9k2m7fq3zIndexRoute: typeof CtrlVx9k2m7fq3zIndexRoute
}

const CtrlVx9k2m7fq3zRouteChildren: CtrlVx9k2m7fq3zRouteChildren = {
  CtrlVx9k2m7fq3zAuditRoute: CtrlVx9k2m7fq3zAuditRoute,
  CtrlVx9k2m7fq3zCategoriesRoute: CtrlVx9k2m7fq3zCategoriesRoute,
  CtrlVx9k2m7fq3zConfigRoute: CtrlVx9k2m7fq3zConfigRoute,
  CtrlVx9k2m7fq3zCountryThemesRoute: CtrlVx9k2m7fq3zCountryThemesRoute,
  CtrlVx9k2m7fq3zExperimentsRoute: CtrlVx9k2m7fq3zExperimentsRoute,
  CtrlVx9k2m7fq3zFlagsRoute: CtrlVx9k2m7fq3zFlagsRoute,
  CtrlVx9k2m7fq3zGreetingsRoute: CtrlVx9k2m7fq3zGreetingsRoute,
  CtrlVx9k2m7fq3zLimitsRoute: CtrlVx9k2m7fq3zLimitsRoute,
  CtrlVx9k2m7fq3zPacksRoute: CtrlVx9k2m7fq3zPacksRouteWithChildren,
  CtrlVx9k2m7fq3zPersonalityRoute: CtrlVx9k2m7fq3zPersonalityRoute,
  CtrlVx9k2m7fq3zPricingRoute: CtrlVx9k2m7fq3zPricingRoute,
  CtrlVx9k2m7fq3zQuizRoute: CtrlVx9k2m7fq3zQuizRoute,
  CtrlVx9k2m7fq3zRecallRoute: CtrlVx9k2m7fq3zRecallRoute,
  CtrlVx9k2m7fq3zRulesRoute: CtrlVx9k2m7fq3zRulesRoute,
  CtrlVx9k2m7fq3zSettingsRoute: CtrlVx9k2m7fq3zSettingsRoute,
  CtrlVx9k2m7fq3zSigninRoute: CtrlVx9k2m7fq3zSigninRoute,
  CtrlVx9k2m7fq3zStoryRoute: CtrlVx9k2m7fq3zStoryRoute,
  CtrlVx9k2m7fq3zUsersRoute: CtrlVx9k2m7fq3zUsersRoute,
  CtrlVx9k2m7fq3zIndexRoute: CtrlVx9k2m7fq3zIndexRoute,
}

const CtrlVx9k2m7fq3zRouteWithChildren = CtrlVx9k2m7fq3zRoute._addFileChildren(
  CtrlVx9k2m7fq3zRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  CtrlVx9k2m7fq3zRoute: CtrlVx9k2m7fq3zRouteWithChildren,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  NotifyFeatureRoute: NotifyFeatureRoute,
  PlacesFeatureRoute: PlacesFeatureRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecoveryRoute: RecoveryRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsFeatureRoute: SettingsFeatureRoute,
  SigninRoute: SigninRoute,
  SplashRoute: SplashRoute,
  TermsRoute: TermsRoute,
  WhyMindropRoute: WhyMindropRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  ApiAuthDriveCallbackRoute: ApiAuthDriveCallbackRoute,
  ApiPublicHooksFireRemindersRoute: ApiPublicHooksFireRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
